# Eureka configuration service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
# Okta configuration service      
okta:
  oauth2:
    issuer: https://dev-95559439.okta.com/oauth2/default
    audience: api://default
